export const tickets = [
  {
    ticketId: 'Ticket-01',
    customerName: 'Philips Henry',
    customerType: 'Premium',
    issueSummary: 'Login error',
    issueDescription: 'Customer is getting error with registered email address.',
    createdDate: '2025-04-01',
    priority: 'High',
    status: 'Open',
  },
  {
    ticketId: 'Ticket-02',
    customerName: 'Steve Daves',
    customerType: 'Standard',
    issueSummary: 'Payment failed',
    issueDescription: 'Cancelled upgrade to Premium, due to payment failed.',
    createdDate: '2025-04-02',
    priority: 'Medium',
    status: 'In Progress',
  },
  {
    ticketId: 'Ticket-03',
    customerName: 'Robert Smith',
    customerType: 'Premium',
    issueSummary: 'App crashing on startup',
    issueDescription: 'The mobile app crashes immediately after launching on iOS.',
    createdDate: '2025-04-03',
    priority: 'Critical',
    status: 'Open',
  },
  {
    ticketId: 'Ticket-04',
    customerName: 'Michael Johnson',
    customerType: 'Standard',
    issueSummary: 'Unable to reset password',
    issueDescription: 'User does not receive reset password email.',
    createdDate: '2025-04-04',
    priority: 'Low',
    status: 'Closed',
  },
  {
    ticketId: 'Ticket-05',
    customerName: 'Belly Ellison',
    customerType: 'Premium',
    issueSummary: 'Bug in dashboard charts',
    issueDescription: 'Bar chart data does not update in real time.',
    createdDate: '2025-04-05',
    priority: 'Medium',
    status: 'In Progress',
  },
  {
    ticketId: 'Ticket-06',
    customerName: 'Logan Paul',
    customerType: 'Standard',
    issueSummary: 'Login failure on mobile app',
    issueDescription: 'Users are unable to log in using the mobile app on iOS 17.',
    createdDate: '2025-04-06',
    priority: 'High',
    status: 'Open',
  },
];
