const data = [
    {
        img: '/src/assets/build1.jpg',
        title: 'Parvati Residency',
        company: 'Dinesh Constructions',
        location: 'hyderabd',
        price: '100',
        area: '1200sqft',
        bedrooms: '5',
        bathrooms: '5',
        amenities: true,
        available: false,
        Contactnow: true,
        verified: true,
    },
    {
        img: '/src/assets/build2.jpg',
        title: 'Sundaram Residency',
        company: 'Rohan Constructions',
        location: 'hyderabd',
        price: '58lakhs',
        area: '800sqft',
        bedrooms: '2',
        bathrooms: '3',
        amenities: true,
        available: true,
        Contactnow: false,
        verified: true,
    },
    {
        img: '/src/assets/build3.jpg',
        title: 'Tulasi Vanam',
        company: 'John Constructions',
        location: 'Ahmedguda',
        price: '29lakhs',
        area: '900sqft',
        bedrooms: '2',
        bathrooms: '2',
        amenities: false,
        available: true,
        Contactnow: false,
        verified: true,
    },
    {
        img: '/src/assets/build4.jpg',
        title: 'Naira Builders',
        company: 'Hridya Constructions',
        location: 'Banglore',
        price: '1.2crores',
        area: '1300sqft',
        bedrooms: '4',
        bathrooms: '5',
        amenities: true,
        available: false,
        Contactnow: true,
        verified: true,
    },
    {
        img: '/src/assets/build5.jpg',
        title: 'Kashish Homes',
        company: 'ksdl Constructions',
        location: 'hyderabad',
        price: '40lakhs',
        area: '400sqft',
        bedrooms: '2',
        bathrooms: '3',
        amenities: true,
        available: true,
        Contactnow: true,
        verified: true,
    },
    {
        img: '/src/assets/build6.jpg',
        title: 'Charan Residency',
        company: 'shyam Constructions',
        location: 'hyderabad',
        price: '1crore',
        area: '1300sqft',
        bedrooms: '4',
        bathrooms: '5',
        amenities: true,
        available: false,
        Contactnow: true,
        verified: true,
    },
];

export default data;