export const metrics = [
    {
      type: "Steps",
      icon: "bi-shoe-prints",
      achieved: 8000,
      goal: 10000,
      description: "Track your daily steps and stay active.",
      dateRange: "April 10 - April 16",
      backgroundImage: "./src/assets/steps.jpg", 
      category: "Fitness",
      owner: "Aman Kumar",
      lastUpdated: "2025-04-10",
      progressHistory: [
        { date: "Apr 1", value: 5000, unit: "steps" },
        { date: "Apr 2", value: 7500, unit: "steps" },
      ],
    },
    {
      type: "Water",
      icon: "bi-droplet",
      achieved: 6,
      goal: 8,
      description: "Stay hydrated by tracking your daily water intake.",
      dateRange: "April 05 - April 12",
      backgroundImage: "./src/assets/water.jpg",
      category: "Hydration",
      owner: "Sandeep Singh",
      lastUpdated: "2025-04-09",
      progressHistory: [
        { date: "Apr 1", value: 5, unit: "glasses" },
        { date: "Apr 2", value: 6, unit: "glasses" },
      ],
    },
    {
      type: "Calories",
      icon: "bi-fire",
      achieved: 1800,
      goal: 2000,
      description: "Keep an eye on your daily caloric intake.",
      dateRange: "April 02 - April 09",
      backgroundImage: "./src/assets/calories.jpg",
      category: "Nutrition",
      owner: "Sureshh Mandal",
      lastUpdated: "2025-04-11",
      progressHistory: [
        { date: "Apr 1", value: 1600, unit: "kcal" },
        { date: "Apr 2", value: 1800, unit: "kcal" },
      ],
    },
    {
      type: "Workout",
      icon: "bi-heart-pulse",
      achieved: 40,
      goal: 60,
      description: "Track total minutes of workout this week.",
      dateRange: "April 01 - April 07",
      backgroundImage: "./src/assets/workout.jpg",
      category: "Exercise",
      owner: "Dhruv Sharma",
      lastUpdated: "2025-04-08",
      progressHistory: [
        { date: "Apr 1", value: 20, unit: "mins" },
        { date: "Apr 2", value: 20, unit: "mins" },
      ],
    },
  ];